import type { Course, CoursesData } from './types';

export const coursesData: CoursesData = {
  bca: {
    id: 'bca',
    name: 'BCA',
    fullName: 'Bachelors of Computer Application',
    duration: '4 Years',
    totalSemesters: 8,
    icon: 'GraduationCap',
    description: 'Degree is a professional degree. The course is designed to provide students with the knowledge and skills required to succeed in computer science and information technology.',
    semesters: [
      {
        id: 1,
        name: 'Semester 1',
        subjects: [
          {
            id: '1',
            name: 'C',
            code: 'BCA101',
            icon: '📊',
            description: 'Master the fundamentals of data organization and algorithms.',
            resources: {
              notes: [
                { id: 1, label: 'Link 1 II', url: '#', type: 'pdf' },
              ],
              pyqs: [
                { id: 1, label: 'Data structures summer 2019', url: '#', type: 'pdf' },
              ],
              lectures: [
                { id: 1, label: 'Link 1 II', url: '#', type: 'youtube' },
              ],
              practicals: [{ id: 1, label: 'Link 1 II', url: '#', type: 'pdf' }],
            },
          },
          {
            id: '2',
            name: 'CAO',
            code: 'BCA102',
            icon: '📜',
            description: 'Explore the foundational document of Indian democracy.',
            resources: { notes: [], pyqs: [], lectures: [], practicals: [] },
          },
          {
            id: '3',
            name: 'MF',
            code: 'BCA103',
            icon: '🗄️',
            description: 'Learn to design, implement, and manage databases effectively.',
            resources: { notes: [], pyqs: [], lectures: [], practicals: [] },
          },
          {
            id: 'English',
            name: 'English',
            code: 'BCA104',
            icon: '🌐',
            description: 'Dive into modern web development. HTML, CSS, JavaScript, and frameworks.',
            resources: { notes: [], pyqs: [], lectures: [], practicals: [] },
          },
          { id: '5', name: 'Vedic maths', code: 'BCA105', icon: '⚡', description: 'Master object-oriented programming with C++.', resources: { notes: [], pyqs: [], lectures: [], practicals: [] } },
          { id: '6', name: 'EVS', code: 'BCA106', icon: '💻', description: 'Understand how operating systems work.', resources: { notes: [], pyqs: [], lectures: [], practicals: [] } },
        ],
      },
      
      /* !!!!!!!!!!!          BCA Semester 2         !!!!!!!!!!*/
      { id: 2, name: 'Semester 2', subjects: [
        {
          id: 'data-structure',
          name: 'Data Structure',
          code: 'BCA101',
          icon: '📊',
          description: 'Master the fundamentals of data organization and algorithms.',
          resources: {
            notes: [],
            pyqs: [
              { id: 1, label: 'Data structures summer 2019',   url: 'https://www.rtmnuonline.com/papers/bca-3-sem-data-structures-2227-summer-2019.pdf', type: 'pdf' },
              { id: 2, label: 'Data structures summer 2018_1', url: 'https://www.rtmnuonline.com/papers/bca-3-sem-data-structures-paper-3-summer-2018.pdf', type: 'pdf' },
              { id: 3, label: 'Data structures summer 2018_2', url: 'https://www.rtmnuonline.com/papers/bca-3-sem-data-structures-summer-2018.pdf', type: 'pdf' },
              { id: 4, label: 'Data structures winter 2018', url: 'https://www.rtmnuonline.com/papers/bca-3-sem-data-structures-winter-2018.pdf', type: 'pdf' },
              { id: 5, label: 'Data structures summer 2017', url: 'https://www.rtmnuonline.com/papers/bca-3-sem-data-structures-summer-2017.pdf', type: 'pdf' },
              { id: 6, label: 'Data structures winter 2017', url: 'https://www.rtmnuonline.com/papers/bca-3-sem-data-structures-winter-2017.pdf', type: 'pdf' },
              { id: 7, label: 'Data structures summer 2016', url: 'https://www.rtmnuonline.com/papers/bca-3-sem-data-structures-summer-2016.pdf', type: 'pdf' },
              { id: 8, label: 'Data structures winter 2016',url: 'https://www.rtmnuonline.com/papers/bca-3-sem-data-structures-winter-2016.pdf', type: 'pdf' },
            ],
            lectures: [
              { id: 1, label: 'Link 1 ', url: 'https://youtu.be/MdG0Vw9f1A4?si=QmF6df5SHgZDYQHo', type: 'youtube' },
              { id: 2, label: 'Link 2 ', url: 'https://youtu.be/J0OvDNmAWNw?si=nVjGorUrDjT_szES', type: 'youtube' },
              { id: 3, label: 'Link 3 ', url: 'https://youtu.be/OkS9YkfW50s?si=K38UEmaOUJO1Vlch', type: 'youtube' },
              { id: 4, label: 'Link 4 ', url: 'https://youtu.be/0rIcIgpl664?si=OdJqoytAzn1qgmlQ', type: 'youtube' },
              { id: 5, label: 'Link 5 ', url: 'https://youtube.com/playlist?list=PLqleLpAMfxGAf5rrWdm92WMK3-gsrxgz5&si=GDZBrnXzwnYeksqi', type: 'youtube' },
              { id: 6, label: 'Link 6 ', url: 'https://youtu.be/8TVaEGeaGGc?si=A-JLzxn_8XkO-Bo9', type: 'youtube' },
              { id: 7, label: 'Link 7 ', url: 'https://youtu.be/zeNnWyEcqSk?si=RJXNYpKpsn4fxUmm', type: 'youtube' },
              { id: 8, label: 'Link 8 ', url: 'https://youtu.be/3Ut-Hha-tmk?si=XuCrUhXS24rCUM2U', type: 'youtube' },
            ],
            practicals: [{ id: 1, label: 'Link 1 II', url: '#', type: 'pdf' }],
          },
        },
        
        {
          id: 'constitution-india',
          name: 'Constitution of India',
          code: 'BCA102',
          icon: '📜',
          description: 'Explore the foundational document of Indian democracy.',
          resources: { 
            notes: [], 
            pyqs: [
              { id: 1, label: 'link 1', url: 'https://i.postimg.cc/gk82SYrg/IMG-20250520-WA0017.jpg', type: 'external' },
              { id: 2, label: 'link 2', url: 'https://www.awesomescreenshot.com/image/57502621?key=984fb4f9fc4ad007e0b82bdcf190c914', type: 'external' },
            ], 
            lectures: [
              { id: 1, label: 'Link 1 ', url: 'https://youtube.com/playlist?list=PLIEVEMAFhG48wZr7qyD4coAuF0EgieTz-&si=iqqsz9crtgRbSEf5', type: 'youtube' },
              { id: 2, label: 'Link 2 ', url: 'https://youtube.com/playlist?list=PLNpnnvxnB2dvFiYlWGsRSpoJme9NaPgle&si=cJ7cg2F9uR2Ucx5e', type: 'youtube' },
              { id: 3, label: 'Link 3 ', url: 'https://youtu.be/KpkoDha-gR4?si=3cqMfslbRddKfPPh', type: 'youtube' },
              { id: 4, label: 'Link 4 ', url: 'https://youtu.be/W-OikE_-n-o?si=HyV2aYtNHOuSbsZY', type: 'youtube' },
              { id: 5, label: 'Link 5 ', url: 'https://youtu.be/7dxt1vcJQQk?si=ovGizf7FZrkFdSg3', type: 'youtube' },
              { id: 6, label: 'Link 6 ', url: 'https://youtu.be/jpU73yXBIWo?si=nPRtMbO9155JGG0Y', type: 'youtube' },
              { id: 7, label: 'Link 7 ', url: 'https://youtu.be/RbsVIvUQEBA?si=wMfjAX2RhJXL1o7I', type: 'youtube' },
              { id: 8, label: 'Link 8',  url: 'https://youtu.be/Dl85IEp8IRs?si=KpdLxq9_AJ1xc9JE', type: 'youtube' },  
              { id: 9, label: 'Link 9',  url: 'https://youtu.be/IusiYyQBTfo?si=-wW5a85NT5muGFhK', type: 'youtube' }, 
              { id: 10,label: 'Link 10', url: 'https://youtu.be/B1Ysu9xlmW0?si=XY-JeJCBiIij7dDp', type: 'youtube' },
            ], 
            practicals: [] 
          },
        },

        {
          id: 'web-technology-sem2',
          name: 'Web Technology',
          code: 'BCA102',
          icon: '🌐',
          description: 'Dive into modern web development. HTML, CSS, JavaScript, and frameworks.',
          resources: { 
            notes: [], 
            pyqs: [
              { id: 1, label: 'Web Technology summer 2016', url: 'https://www.rtmnuonline.com/papers/bca-3-sem-web-technology-summer-2016.pdf', type: 'pdf' },
              { id: 2, label: 'Web Technology winter 2016', url: 'https://www.rtmnuonline.com/papers/bca-3-sem-web-technology-winter-2016.pdf', type: 'pdf' },
              { id: 3, label: 'Web Technology summer 2019', url: 'https://www.rtmnuonline.com/papers/bca-4-sem-web-technology-2-2235-summer-2019.pdf', type: 'pdf' },
              { id: 4, label: 'Web Technology summer 2018', url: 'https://www.rtmnuonline.com/papers/bca-3-sem-web-technology-summer-2018.pdf', type: 'pdf' },
              { id: 5, label: 'Web Technology winter 2018', url: 'https://www.rtmnuonline.com/papers/bca-3-sem-web-technology-winter-2018.pdf', type: 'pdf' },
              { id: 6, label: 'Web Technology summer 2017', url: 'https://www.rtmnuonline.com/papers/bca-3-sem-web-technology-summer-2017.pdf', type: 'pdf' },
              { id: 7, label: 'Web Technology winter 2017', url: 'https://www.rtmnuonline.com/papers/bca-3-sem-web-technology-winter-2017.pdf', type: 'pdf' },
            ], 
            lectures: [
              { id: 1, label: 'Link 1 ', url: 'https://youtu.be/1V9mhVgVH3A?si=na6l6GkjruofsR4A', type: 'youtube' },
              { id: 2, label: 'Link 2 ', url: 'https://youtube.com/playlist?list=PLrjkTql3jnm8d1ddpVKifXO_fPjSKATCp&si=7iDNZzFCcK9DXiC_', type: 'youtube' },
              { id: 3, label: 'Link 3 ', url: 'https://youtube.com/playlist?list=PLV8vIYTIdSnbwIFENjqBK7yyAkSVSoLBC&si=_k06Hv9tmzDDbJmU', type: 'youtube' },
            ], 
            practicals: [] 
          },
        },
        
        {
          id: 'dbms-sem2',
          name: 'Database Management System',
          code: 'BCA103',
          icon: '🗄️',
          description: 'Learn to design, implement, and manage databases effectively.',
          resources: { 
            notes: [], 
            pyqs: [
              { id: 1, label: 'DBMS summer 2019',   url: 'https://www.rtmnuonline.com/papers/bca-3-sem-data-base-management-system-2226-summer-2019.pdf', type: 'pdf' },
              { id: 2, label: 'DBMS summer 2018',   url: 'https://www.rtmnuonline.com/papers/bca-3-sem-database-management-system-paper-2-summer-2018.pdf', type: 'pdf' },
              { id: 3, label: 'DBMS summer 2018_2', url: 'https://www.rtmnuonline.com/papers/bca-3-sem-database-management-system-summer-2018.pdf', type: 'pdf' },
              { id: 4, label: 'DBMS winter 2018', url: 'https://www.rtmnuonline.com/papers/bca-3-sem-database-management-system-winter-2018.pdf', type: 'pdf' },
              { id: 5, label: 'DBMS summer 2017', url: 'https://www.rtmnuonline.com/papers/bca-3-sem-database-management-system-summer-2017.pdf', type: 'pdf' },
              { id: 6, label: 'DBMS winter 2017', url: 'https://www.rtmnuonline.com/papers/bca-3-sem-database-management-system-winter-2017.pdf', type: 'pdf' },
              { id: 7, label: 'DBMS summer 2016', url: 'https://www.rtmnuonline.com/papers/bca-3-sem-database-management-system-summer-2016.pdf', type: 'pdf' },
              { id: 8, label: 'DBMS winter 2016',url: 'https://www.rtmnuonline.com/papers/bca-3-sem-database-management-system-winter-2016.pdf', type: 'pdf' },
            ], 
            lectures: [
              { id: 1, label: 'Link 1 ', url: 'https://youtu.be/YRnjGeQbsHQ?si=Yx00NuCfJHqN4-e3', type: 'youtube' },
              { id: 2, label: 'Link 2 ', url: 'https://youtu.be/jzuzxEFoiss?si=JO-X39h39MWq2v9I', type: 'youtube' },
              { id: 3, label: 'Link 3 ', url: 'https://youtu.be/dl00fOOYLOM?si=kyrAI2Q8i_v62W6a', type: 'youtube' },
              { id: 4, label: 'Link 4 ', url: 'https://youtu.be/J0OvDNmAWNw?si=I-cJuHjL6gI-5Zjv', type: 'youtube' },
              { id: 5, label: 'Link 5 ', url: 'https://youtu.be/viJzDvom2Yc?si=0pycMTlnkqOtY8al', type: 'youtube' },
              { id: 6, label: 'Link 6 ', url: 'https://youtube.com/playlist?list=PLYwpaL_SFmcBU4HS74xGTK1cAFbY0rdVY&si=gnYk_t18icBGYPj-', type: 'youtube' },
              { id: 7, label: 'Link 7 ', url: 'https://youtube.com/playlist?list=PLqleLpAMfxGDEClbx9ymd-KWDDJrx_W8C&si=MS46cOJ9IeFcT4Cp', type: 'youtube' },
              { id: 8, label: 'Link 8',  url: 'https://youtube.com/playlist?list=PLBvTTYUOHEmcbkKi6G-7tg0sUnQwujApt&si=qVYZKuN3T42Lw_-o', type: 'youtube' },  
              { id: 9, label: 'Link 9  (Unit- 1)', url: 'https://youtu.be/ptlIJiIByMc?si=UeMYRSvjUQDW0PrY', type: 'youtube' }, 
              { id: 10,label: 'Link 10 (Unit- 2)', url: 'https://youtu.be/jRReZoQi1hw?si=QwQbFJAMZqsu9MEX', type: 'youtube' },
              { id: 11,label: 'Link 11 (Unit- 3)', url: 'https://youtu.be/VAd8Audkxro?si=7dZWox_h3kK5kpfa', type: 'youtube' },
              { id: 12,label: 'Link 12 (Unit- 4)', url: 'https://youtu.be/0Skq_YqrHjg?si=ZxHTvNHy4f21ol7t', type: 'youtube' },
              { id: 13,label: 'Link 13', url: 'https://youtu.be/oR6IXFrJBEk?si=uNYjX4mp-M2LD08h', type: 'youtube' },
            ], 
            practicals: [] 
          }
        },
        { id: 'cpp-sem2', 
          name: 'C++', code: 'BCA105', 
          icon: '⚡', 
          description: 'Master object-oriented programming with C++.', 
          resources: { 
            notes: [], 
            pyqs: [
              { id: 1, label: ' C++ summer 2017',  url: 'https://www.rtmnuonline.com/papers/bca-2-sem-programming-in-cpp-summer-2017.pdf', type: 'pdf' },
              { id: 2, label: ' C++ summer 2018',  url: 'https://www.rtmnuonline.com/papers/bca-2-sem-programming-in-cpp-2018.pdf', type: 'pdf' },
              { id: 3, label: ' C++ summer 2018_2',url: 'https://www.rtmnuonline.com/papers/bca-2-sem-programming-in-cpp-paper-1-summer-2018.pdf', type: 'pdf' },
              { id: 4, label: ' C++ winter 2018',  url: 'https://www.rtmnuonline.com/papers/bca-2-sem-programming-in-cpp-winter-2018.pdf', type: 'pdf' },
              { id: 5, label: ' C++ winter 2017',  url: 'https://www.rtmnuonline.com/papers/bca-2-sem-programming-in-cpp-winter-2017.pdf', type: 'pdf' },
              { id: 6, label: ' C++ winter 2016',  url: 'https://www.rtmnuonline.com/papers/bca-2-sem-programing-in-cpp-summer-2016.pdf', type: 'pdf' },
              { id: 7, label: ' C++ winter 2016_2',  url: 'https://www.rtmnuonline.com/papers/bca-2-sem-programming-in-cpp-winter-2016.pdf', type: 'pdf' },
              { id: 8, label: ' C++ winter 2015',  url: 'https://www.rtmnuonline.com/papers/bca-2-sem-programming-in-cpp-winter-2015.pdf', type: 'pdf' },
            
            ], lectures: [
              { id: 1, label: 'Link 1 ', url: 'https://youtube.com/playlist?list=PL724pdDXl9Q0yZUx9bkqarHO584JOsKfE&si=Tt7SUIIwwmYm2f_a', type: 'youtube' },
              { id: 2, label: 'Link 2 ', url: 'https://youtube.com/playlist?list=PLmRclvVt5DtlXMvqL0zDqQu9Cvy6rsmd4&si=DN_whLhVx31_Pmuv', type: 'youtube' },
              { id: 3, label: 'Link 3 ', url: 'https://youtube.com/playlist?list=PLqleLpAMfxGDq9Ehl8FUstcRrCRQPQO7n&si=ltxcBEEYDa6UdO3K', type: 'youtube' },
              { id: 4, label: 'Link 4 ', url: 'https://youtu.be/stqrJl3pIaI?si=eYa1p3seFIDjO0RD', type: 'youtube' },
              { id: 5, label: 'Link 5 ', url: 'https://youtu.be/OQ0En1dQ3zI?si=pXqWcqDoKGqFc3AZ', type: 'youtube' },
              { id: 6, label: 'Link 6 ', url: 'https://youtu.be/mlIUKyZIUUU?si=N-C1uF9w3rp0VbFv', type: 'youtube' },
              { id: 7, label: 'Link 7 ', url: 'https://youtube.com/playlist?list=PLxCzCOWd7aiF6yRNI5OHQsnUJQfl7Geqj&si=jV9OsM6ZAyxfe1HY', type: 'youtube' },
              { id: 8, label: 'Link 8 ', url: 'https://youtu.be/9roJTTghZJI?si=yi4iSn53TeDTIBii', type: 'youtube' },
              { id: 9, label: 'Link 9 ', url: 'https://youtu.be/oi1ffu6lBXE?si=ywnaLOR6HpE55VJn', type: 'youtube' },
              { id: 10, label: 'Link 10', url: 'https://youtu.be/oi1ffu6lBXE?si=ywnaLOR6HpE55VJn', type: 'youtube' },
            ], 
            practicals: [] } },
        
            { id: 'operating-system-sem2', 
            name: 'Operating System', 
            code: 'BCA106', icon: '💻', 
            description: 'Understand how operating systems work.', 
            resources: { 
              notes: [], 
              pyqs: [
                { id: 1, label: ' Operating System summer 2018',   url: 'https://www.rtmnuonline.com/papers/bca-1-sem-operating-systems-paper-5-summer-2018.pdf', type: 'pdf' },
                { id: 2, label: ' Operating System winter 2017',   url: 'https://www.rtmnuonline.com/papers/bca-1-sem-operating-systems-winter-2017.pdf', type: 'pdf' },
                { id: 3, label: ' Operating System summer 2017',   url: 'https://www.rtmnuonline.com/papers/bca-1-sem-operating-systems-summer-2017.pdf', type: 'pdf' },
                { id: 4, label: ' Operating System summer 2024',   url: 'https://www.rtmnuonline.com/papers/bca-2-sem-linux-operating-system-1304-summer-2024.pdf', type: 'pdf' },
                { id: 5, label: ' Operating System summer 2019',   url: 'https://www.rtmnuonline.com/papers/bca-2-sem-linux-operating-system-2223-summer-2019.pdf', type: 'pdf' },
                { id: 6, label: ' Operating System summer 2018_2',   url: 'https://www.rtmnuonline.com/papers/bca-2-sem-linux-operating-system-2018.pdf', type: 'pdf' },
                { id: 7, label: ' Operating System summer 2017_2',   url: 'https://www.rtmnuonline.com/papers/bca-2-sem-linux-operating-system-2017.pdf', type: 'pdf' },
                { id: 8, label: ' Operating System summer 2017_1', url: 'https://www.rtmnuonline.com/papers/bca-2-sem-linux-operating-system-summer-2017.pdf', type: 'pdf' },
                ], 
              lectures: [
                { id: 1, label: 'Link 1 ', url: 'https://youtu.be/xw_OuOhjauw?si=AKRM9F2qZJBIXS-j', type: 'youtube' },
                { id: 2, label: 'Link 2 ', url: 'https://youtu.be/8XBtAjKwCm4?si=L3dllyH_lYBQaWUy', type: 'youtube' },
                { id: 3, label: 'Link 3 ', url: 'https://youtu.be/A4G0hOI6XyQ?si=hXf7JWhHz2qKkJyM', type: 'youtube' },
                { id: 4, label: 'Link 4 ', url: 'https://youtube.com/playlist?list=PLuAADu3OvBt6kxY_YZSSYaaTWkgYrCQVO&si=SOeDjC6_CmNmpmIB', type: 'youtube' },
                { id: 5, label: 'Link 5 ', url: 'https://youtube.com/playlist?list=PLxCzCOWd7aiGz9donHRrE9I3Mwn6XdP8p&si=1s4sUwTJInjWMjpD', type: 'youtube' },
                { id: 6, label: 'Link 6 ', url: 'https://youtube.com/playlist?list=PLBlnK6fEyqRiVhbXDGLXDk_OQAeuVcp2O&si=nVpzri-9H_R9OJHs', type: 'youtube' },
                { id: 7, label: 'Link 7 ', url: 'https://youtube.com/playlist?list=PL23dd-8zssJDbCZI4Rle3vuQokIAdiDdB&si=8Ms8SXpuhlBnku-L', type: 'youtube' },
                { id: 8, label: 'Link 8 ', url: 'https://youtube.com/playlist?list=PLmXKhU9FNesSFvj6gASuWmQd23Ul5omtD&si=kfmrvkJlTcc7kHbS', type: 'youtube' },
                { id: 9, label: 'Link 9 ', url: 'https://youtube.com/playlist?list=PLG9aCp4uE-s17rFjWM8KchGlffXgOzzVP&si=zZlP4oQHi-ctWDc5', type: 'youtube' },
                { id: 10,label: 'Link 10 ', url: 'https://youtube.com/playlist?list=PLV8vIYTIdSnZ67NQObdXE0gFjrzPrNKHp&si=2ipfEHzxrG0rc0dn', type: 'youtube' },
                { id: 11,label: 'Link 11 ', url: 'https://youtube.com/playlist?list=PLqcuf9-ILPYARwquS3KOD3bDe0NSaD-oK&si=ZhAB8Pl9pHLFz3Aj', type: 'youtube' },
                { id: 12,label: 'Link 12 ', url: 'https://youtube.com/playlist?list=PLdo5W4Nhv31a5ucW_S1K3-x6ztBRD-PNa&si=COQ8zrzb8QFlPXTd', type: 'youtube' },
              ], 
              practicals: [] } },
            ],
          },

    /* SEMESTER 3 BCA YEAAAAAAAAAAAAAAAAAAAAAAAAHHHHHHHHH!!!!!!!! */
      { id: 3, 
        name: 'Semester 3', 
        subjects: [
          {
            id: 'Java',
            name: 'Java Programming ',
            code: 'BCA301',
            icon: '☕',
            description: 'Learn the fundamentals of Java programming.',
            resources: {
              notes: [],
              pyqs: [
                { id: 1, label: 'Link 1', url: '', type: 'pdf' },
                { id: 2, label: 'Link 2', url: '', type: 'pdf' },
                { id: 3, label: 'Link 3', url: '', type: 'pdf' },
                { id: 4, label: 'Link 4', url: '', type: 'pdf' },
                { id: 5, label: 'Link 5', url: '', type: 'pdf' },
                { id: 6, label: 'Link 6', url: '', type: 'pdf' },
                { id: 7, label: 'Link 7', url: '', type: 'pdf' },
                { id: 8, label: 'Link 8',url: '', type: 'pdf' },
              ],
              lectures: [
                { id: 1, label: 'Link 1 ', url: 'https://youtube.com/playlist?list=PLlg3g5kppv-9FB8xrju6852QezyQUPUHZ&si=_lcLLza5Wa42sjXx', type: 'youtube' },
                { id: 2, label: 'Link 2 ', url: 'https://youtu.be/Byf6xOYdNcw?si=z1WqStt9ubW53hzD', type: 'youtube' },
                { id: 3, label: 'Link 3 ', url: 'https://youtube.com/playlist?list=PLXIPR4CD0noqAMtGtjXnIhcX3ChbLbGHr&si=I0Slla3JVDcn8pkJ', type: 'youtube' },
                { id: 4, label: 'Link 4 ', url: 'https://youtube.com/playlist?list=PLu0W_9lII9agS67Uits0UnJyrYiXhDS6q&si=hlRNgEP7iJrDpShN', type: 'youtube' },
                { id: 5, label: 'Link 5 ', url: 'https://youtu.be/UmnCZ7-9yDY?si=mFg59dKxePzTNosI', type: 'youtube' },
                { id: 6, label: 'Link 6 ', url: 'https://youtube.com/playlist?list=PLqleLpAMfxGAdqZeY_4uVQOPCnAjhH-eT&si=s_hZPiL8Soy8LqDo', type: 'youtube' },
                { id: 7, label: 'Link 7 ', url: 'https://youtu.be/32tp0Ot2JtU?si=TihILaK_iXssx-DB', type: 'youtube' },
                { id: 8, label: 'Link 8 ', url: 'https://youtu.be/LepLT82RtxA?si=b1f4AhTTS6lawqjZ', type: 'youtube' },
                { id: 9, label: 'Link 9 ', url: 'https://youtube.com/playlist?list=PL78RhpUUKSweClRi_l05UgfE3053-zkRf&si=tDPTs5tS7hkA0Bs3', type: 'youtube' },
                { id: 10,label: 'Link 10', url: 'https://youtube.com/playlist?list=PLr3OnN7KdzehfjBqP7o5pyvlcT4O2zi4n&si=liOvd9sAWeF2AWTF', type: 'youtube' },
                { id: 11,label: 'Link 11', url: 'https://youtube.com/playlist?list=PL-G5fgAX3nWoMC2TjXd60tmOg_I-f_5Qh&si=LyQITM1H0peu5uFp', type: 'youtube' },
              ],
              practicals: [{ id: 1, label: 'Link 1 II', url: '#', type: 'pdf' }],
            },
          },

          {
            id: 'Software-Enginnering',
            name: 'Software Enginnering',
            code: 'BCA302',
            icon: '⚙️',
            description: 'Have Fun with engineering!!',
            resources: {
              notes: [],
              pyqs: [
                { id: 1, label: 'Link 1', url: '', type: 'pdf' },
                { id: 2, label: 'Link 3', url: '', type: 'pdf' },
                { id: 3, label: 'Link 4', url: '', type: 'pdf' },
                { id: 4, label: 'Link 5', url: '', type: 'pdf' },
                { id: 5, label: 'Link 6', url: '', type: 'pdf' },
                { id: 6, label: 'Link 7', url: '', type: 'pdf' },
                { id: 7, label: 'Link 8', url: '', type: 'pdf' },
                { id: 8, label: 'Link 9',url: '', type: 'pdf' },
              ],
              lectures: [
                { id: 1, label: 'Link 1 ', url: 'https://youtube.com/playlist?list=PLlg3g5kppv-9eOE-Xt4newjrufPcKRG_Z&si=GJyFbZ0H6etqoOOh', type: 'youtube' },
                { id: 2, label: 'Link 2 ', url: 'https://youtube.com/playlist?list=PLXIPR4CD0nooj3GkNbNB4CykWL9WEBIlC&si=WJFO7zUMBPE3cZVu', type: 'youtube' },
                { id: 3, label: 'Link 3 ', url: 'https://youtube.com/playlist?list=PLqleLpAMfxGB1g0xlYj2H6lyY2Q2ku7p9&si=PDadEgS2MC-KG5uj', type: 'youtube' },
                { id: 4, label: 'Link 4 ', url: 'https://youtube.com/playlist?list=PLmXKhU9FNesTrw7n8ouPsSLEcduRlENHr&si=Xzj9csuFmSDztqn2', type: 'youtube' },
                { id: 5, label: 'Link 5 ', url: 'https://youtube.com/playlist?list=PLxCzCOWd7aiEed7SKZBnC6ypFDWYLRvB2&si=0xvZmLkG2QoIOs3c', type: 'youtube' },
                { id: 6, label: 'Link 6 ', url: 'https://youtube.com/playlist?list=PLr3OnN7KdzegkcczKY8vcaSWN6clHds8e&si=KY7JcDOpPd4J4SuJ', type: 'youtube' },
                { id: 7, label: 'Link 7 ', url: 'https://youtube.com/playlist?list=PL-G5fgAX3nWoCfOETYwIm6aRLH_0USvSd&si=rWKC8iN3GLdCZI0K', type: 'youtube' },
                { id: 8, label: 'Link 8 ', url: 'https://youtube.com/playlist?list=PL5lGYQg6y9m_B7Gd5tmayScXwiyO0cRat&si=Hm83hMnCGCTYusoV', type: 'youtube' },
              ],
              practicals: [{ id: 1, label: 'Link 1 II', url: '#', type: 'pdf' }],
            },
          },

          {
            id: 'Python',
            name: 'Python Programming',
            code: 'BCA303',
            icon: '🐍',
            description: 'Learn Python and build your stuff',
            resources: {
              notes: [],
              pyqs: [
                { id: 1, label: 'Link 1', url: '', type: 'pdf' },
                { id: 2, label: 'Link 2', url: '', type: 'pdf' },
                { id: 3, label: 'Link 3', url: '', type: 'pdf' },
                { id: 4, label: 'Link 4', url: '', type: 'pdf' },
                { id: 5, label: 'Link 5', url: '', type: 'pdf' },
                { id: 6, label: 'Link 6', url: '', type: 'pdf' },
                { id: 7, label: 'Link 7', url: '', type: 'pdf' },
                { id: 8, label: 'Link 8', url: '', type: 'pdf' },
              ],
              lectures: [
                { id: 1, label: 'Link 1 ', url: 'https://youtube.com/playlist?list=PLqleLpAMfxGClAxSATq06jrPPOGexBKBI&si=ISAyQL6xMutgBrR_', type: 'youtube' },
                { id: 2, label: 'Link 2 ', url: 'https://youtube.com/playlist?list=PLxCzCOWd7aiEb4apyN1Y8mD-QuUTr3SPQ&si=Nzml3KP-M428GGPz', type: 'youtube' },
                { id: 3, label: 'Link 3 ', url: 'https://youtube.com/playlist?list=PL49mRA0Y_C8vu2RWHdPsuRNRAcd89-eaz&si=0t3vexqSh0-hScaa', type: 'youtube' },
                { id: 4, label: 'Link 4 ', url: 'https://youtube.com/playlist?list=PL-vEH_IPWrhDyJv4uK5_Kno83d6VKSOg6&si=0N8fIWTCjRe3c05v', type: 'youtube' },
                { id: 5, label: 'Link 5 ', url: 'https://youtube.com/playlist?list=PLr3OnN7KdzegllewQAwyR5wnZ3rp0UhPF&si=sXYIlznweiIVKouA', type: 'youtube' },
                { id: 6, label: 'Link 6 ', url: 'https://youtu.be/s6VhXiBn-Zg?si=iUx6RKl4SSei89ne', type: 'youtube' },
                { id: 7, label: 'Link 7 ', url: 'https://youtube.com/playlist?list=PLur0XnH30m5y4NfWDgQFkfPgFdFD2Xr5-&si=wzTp2D-Mzw3bldLa', type: 'youtube' },
                { id: 8, label: 'Link 8 ', url: 'https://youtube.com/playlist?list=PLur0XnH30m5xcAmFgkQvN3tg9qkjPJ8zQ&si=7FMBEpD3_WBGA4xt', type: 'youtube' },
                { id: 9, label: 'Link 9 ', url: 'https://youtu.be/XnSasPR2KJI?si=YMb1OPtOUd2yAFyv', type: 'youtube' },
                { id: 10, label: 'Link 10', url: 'https://youtube.com/playlist?list=PLxCzCOWd7aiEb4apyN1Y8mD-QuUTr3SPQ&si=EVANAi3n1sjBKc6F', type: 'youtube' },
                { id: 11, label: 'Link 11', url: 'https://youtube.com/playlist?list=PL-G5fgAX3nWqIWzBDtJ-FIJeesJu_SlVw&si=7SPnVly6igkyPByS', type: 'youtube' },
                { id: 12, label: 'Link 12', url: 'https://youtube.com/playlist?list=PLERZXVMwiajpFoqeQKz3p4EDooFhmJnSo&si=1sEuVdPf8V1M3f4y', type: 'youtube' },
                { id: 13, label: 'Link 13', url: 'https://youtube.com/playlist?list=PLEbnTDJUr_IcBS7XPeqLvFc_xZHmiER-C&si=sRJb4fakVu-5SnbE', type: 'youtube' },
               ],
              practicals: [],
            },
          },

          {
            id: 'Probability-Statistics',
            name: 'Probability & Statistics',
            code: 'BCA304',
            icon: '🧮',
            description: 'Probability increases the chances of success',
            resources: {
              notes: [],
              pyqs: [
                { id: 1, label: 'Link 1', url: '', type: 'pdf' },
                { id: 2, label: 'Link 2', url: '', type: 'pdf' },
                { id: 3, label: 'Link 3', url: '', type: 'pdf' },
                { id: 4, label: 'Link 4', url: '', type: 'pdf' },
                { id: 5, label: 'Link 5', url: '', type: 'pdf' },
                { id: 6, label: 'Link 6', url: '', type: 'pdf' },
                { id: 7, label: 'Link 7', url: '', type: 'pdf' },
                { id: 8, label: 'Link 8', url: '', type: 'pdf' },
              ],
              lectures: [
                { id: 1, label: 'Link 1 ', url: 'https://youtu.be/dx4bqMlATQU?si=5-iWvjsXocrutO70', type: 'youtube' },
                { id: 2, label: 'Link 2 ', url: 'https://youtu.be/ruWsWnik7YY?si=Xo0IFZxHD2XoEcls', type: 'youtube' },
                { id: 3, label: 'Link 3 ', url: 'https://youtube.com/playlist?list=PLEHGYFbPuuME9Gfl5r5CCWCzJ-pRfFVpL&si=B9JlEaQdceFJIlET', type: 'youtube' },
                { id: 4, label: 'Link 4 ', url: 'https://youtube.com/playlist?list=PLxCzCOWd7aiFjZP4z1_3Kr3m3J5wu5Q8V&si=chEZHb5b14SAgve5', type: 'youtube' },
                { id: 5, label: 'Link 5 ', url: 'https://youtube.com/playlist?list=PLU6SqdYcYsfJuwkSQOO5ogFeTGC0mY4ja&si=V6bhR0uJrdtGVBYM', type: 'youtube' },
                { id: 6, label: 'Link 6 ', url: 'https://youtube.com/playlist?list=PLU6SqdYcYsfJPF-4HphQQ8OceDtqhlSW8&si=lDrqQlEl6zcvtXz-', type: 'youtube' },
                { id: 7, label: 'Link 7 ', url: 'https://youtube.com/playlist?list=PLOEeYltRrWu6DgdAAEAo9Uj5jucA0Di5Z&si=anm5C4FhqRf0wLNN', type: 'youtube' },
                { id: 8, label: 'Link 8 ', url: 'https://youtube.com/playlist?list=PLWpLtDYKhjfoDrzfLHxQCbOxyrxPEW1ZP&si=UKdXUSca0Xpf-qaz', type: 'youtube' },
                { id: 9, label: 'Link 9 ', url: 'https://www.youtube.com/live/h3Lo3W5wB04?si=SqUOTNsdjt8kf4f5', type: 'youtube' },
                { id: 10, label: 'Link 10', url: 'https://youtube.com/playlist?list=PLxCzCOWd7aiFjZP4z1_3Kr3m3J5wu5Q8V&si=Lv1_j5AwKt9loK3n', type: 'youtube' },
                { id: 11, label: 'Link 11', url: 'https://youtube.com/playlist?list=PLU6SqdYcYsfLRq3tu-g_hvkHDcorrtcBK&si=DrZSvIHm90cU8Bej', type: 'youtube' },
              ],
              practicals: [],
            },
          },

          {
            id: 'Data-Analytics-Spreadsheets',
            name: 'Data Analytics & Spreadsheets',
            code: 'BCA3012',
            icon: '📊',
            description: 'Data Analytics increases the chances of chances',
            resources: {
              notes: [],
              pyqs: [
                { id: 1, label: 'Link 1', url: '', type: 'pdf' },
                { id: 2, label: 'Link 2', url: '', type: 'pdf' },
                { id: 3, label: 'Link 3', url: '', type: 'pdf' },
                { id: 4, label: 'Link 4', url: '', type: 'pdf' },
                { id: 5, label: 'Link 5', url: '', type: 'pdf' },
                { id: 6, label: 'Link 6', url: '', type: 'pdf' },
                { id: 7, label: 'Link 7', url: '', type: 'pdf' },
                { id: 8, label: 'Link 8', url: '', type: 'pdf' },
              ],
              lectures: [
                { id: 1, label: 'Link 1 ', url: 'https://youtube.com/playlist?list=PL5lGYQg6y9m9nJrJxJjA8K52lBhtuHpB0&si=v0-D4tbw9l0Xkhwn', type: 'youtube' },
                { id: 2, label: 'Link 2 ', url: 'https://youtube.com/playlist?list=PLw1djS7l2tHNR3tjvLsnuxW5XEs4kh6kM&si=1DSxHGD1niixPqfU', type: 'youtube' },
                { id: 3, label: 'Link 3 ', url: 'https://youtu.be/Kjz_DDO4Fzs?si=LxcMR_5Dwl_D1IIU', type: 'youtube' },
                { id: 4, label: 'Link 4 ', url: 'https://youtu.be/OX-iyb-21tk?si=IbqyNJsWFxnx7z_T', type: 'youtube' },
                { id: 5, label: 'Link 5 ', url: 'https://youtube.com/playlist?list=PLEiEAq2VkUUKgEFXH1tBbHwq38oWYDScU&si=ukL7qhEmARcaEQFv', type: 'youtube' },
                { id: 6, label: 'Link 6 ', url: 'https://youtu.be/pCJ15nGFgVg?si=aIQU-AA5i3Z6Z8lz', type: 'youtube' },
                { id: 7, label: 'Link 7 ', url: 'https://youtu.be/kghcAk7l6eA?si=4ntwSWIKhKpsOQrV', type: 'youtube' },
                { id: 8, label: 'Link 8 ', url: 'https://youtube.com/playlist?list=PLoyECfvEFOjYOt0f8CKyj0a_-YnETyKF1&si=_5aCGfihVPylJEeY', type: 'youtube' },
                { id: 9, label: 'Link 9 ', url: 'https://youtube.com/playlist?list=PLoyECfvEFOjZNdBAHDlVlR242FifiYGjl&si=wTxYcLUve1-VvK0x', type: 'youtube' },
                { id: 10, label: 'Link 10', url: 'https://youtu.be/-Tts712mDZs?si=Ux1g3fRGuAzz_btJ', type: 'youtube' },
                { id: 11, label: 'Link 11', url: 'https://youtu.be/-Tts712mDZs?si=fnrWuXEjhQu96PhL', type: 'youtube' },
              ],
              practicals: [],
            },
          },
        ] },
      { id: 4, name: 'Semester 4', subjects: [] },
      { id: 5, name: 'Semester 5', subjects: [] },
      { id: 6, name: 'Semester 6', subjects: [] },
      { id: 7, name: 'Semester 7', subjects: [] },
      { id: 8, name: 'Semester 8', subjects: [] },
    ],
  },
  bsc: {
    id: 'bsc',
    name: 'B.Sc',
    fullName: 'Bachelor of Science',
    duration: '3 Years',
    totalSemesters: 6,
    icon: 'Microscope',
    description: 'Explore scientific concepts and develop analytical skills across various science disciplines.',
    semesters: [
      { id: 1, name: 'Semester 1', subjects: [] },
      { id: 2, name: 'Semester 2', subjects: [] },
      { id: 3, name: 'Semester 3', subjects: [] },
      { id: 4, name: 'Semester 4', subjects: [] },
      { id: 5, name: 'Semester 5', subjects: [] },
      { id: 6, name: 'Semester 6', subjects: [] },
    ],
  },
  bcom: {
    id: 'bcom',
    name: 'B.Com',
    fullName: 'Bachelor of Commerce',
    duration: '3 Years',
    totalSemesters: 6,
    icon: 'Briefcase',
    description: 'Gain expertise in commerce, accounting, and business management.',
    semesters: [
      { id: 1, name: 'Semester 1', subjects: [] },
      { id: 2, name: 'Semester 2', subjects: [] },
      { id: 3, name: 'Semester 3', subjects: [] },
      { id: 4, name: 'Semester 4', subjects: [] },
      { id: 5, name: 'Semester 5', subjects: [] },
      { id: 6, name: 'Semester 6', subjects: [] },
    ],
  },
  ba: {
    id: 'ba',
    name: 'B.A.',
    fullName: 'Bachelor of Arts',
    duration: '3 Years',
    totalSemesters: 6,
    icon: 'ScrollText',
    description: 'Explore humanities, social sciences, and liberal arts subjects.',
    semesters: [
      { id: 1, name: 'Semester 1', subjects: [] },
      { id: 2, name: 'Semester 2', subjects: [] },
      { id: 3, name: 'Semester 3', subjects: [] },
      { id: 4, name: 'Semester 4', subjects: [] },
      { id: 5, name: 'Semester 5', subjects: [] },
      { id: 6, name: 'Semester 6', subjects: [] },
    ],
  },
  bba: {
    id: 'bba',
    name: 'BBA',
    fullName: 'Bachelor of Business Administration',
    duration: '3 Years',
    totalSemesters: 6,
    icon: 'BarChartBig',
    description: 'Develop business management and administration skills.',
    semesters: [
      { id: 1, name: 'Semester 1', subjects: [] },
      { id: 2, name: 'Semester 2', subjects: [] },
      { id: 3, name: 'Semester 3', subjects: [] },
      { id: 4, name: 'Semester 4', subjects: [] },
      { id: 5, name: 'Semester 5', subjects: [] },
      { id: 6, name: 'Semester 6', subjects: [] },
    ],
  },
  btech: {
    id: 'btech',
    name: 'B.Tech',
    fullName: 'Bachelor of Technology',
    duration: '4 Years',
    totalSemesters: 8,
    icon: 'Laptop',
    description: 'Engineer the future with cutting-edge technology and innovation.',
    semesters: [],
  },
};

export function getCourses() {
  return Object.values(coursesData);
}

export function getCourseById(id: string): Course | undefined {
  return coursesData[id];
}
