
'use client';

import { useState } from 'react';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import * as z from 'zod';
import { Button } from '@/components/ui/button';
import {
  Form,
    FormControl,
      FormField,
        FormItem,
          FormLabel,
            FormMessage,
            } from '@/components/ui/form';
            import { Input } from '@/components/ui/input';
            import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
            import { useToast } from '@/hooks/use-toast';
            import Link from 'next/link';
            import { Loader2 } from 'lucide-react';
            import { useAuth } from '@/firebase';
            import { sendPasswordResetEmail } from 'firebase/auth';

            const formSchema = z.object({
              email: z.string().email({ message: 'Invalid email address.' }),
              });

              export default function ForgotPasswordPage() {
                const [isLoading, setIsLoading] = useState(false);
                  const [emailSent, setEmailSent] = useState(false);
                    const { toast } = useToast();
                      const auth = useAuth();

                        const form = useForm<z.infer<typeof formSchema>>({
                            resolver: zodResolver(formSchema),
                                defaultValues: {
                                      email: '',
                                          },
                                            });

                                              async function onSubmit(values: z.infer<typeof formSchema>) {
                                                  if (!auth) return;
                                                      setIsLoading(true);
                                                          try {
                                                                await sendPasswordResetEmail(auth, values.email);
                                                                      setEmailSent(true);
                                                                          } catch (error: any) {
                                                                                toast({
                                                                                        variant: 'destructive',
                                                                                                title: 'Error',
                                                                                                        description: error.message || 'Failed to send password reset email. Please try again.',
                                                                                                              });
                                                                                                                  } finally {
                                                                                                                        setIsLoading(false);
                                                                                                                            }
                                                                                                                              }

                                                                                                                                return (
                                                                                                                                    <div className="flex min-h-screen flex-col items-center justify-center bg-background px-4">
                                                                                                                                          <h1 className="mb-8 text-5xl font-bold text-white">LearNova</h1>
                                                                                                                                                <Card className="w-full max-w-md border-white">
                                                                                                                                                        <CardHeader>
                                                                                                                                                                  <CardTitle>{emailSent ? 'Check Your Email' : 'Forgot Password'}</CardTitle>
                                                                                                                                                                            <CardDescription>
                                                                                                                                                                                        {emailSent
                                                                                                                                                                                                      ? `We sent a password reset link to ${form.getValues('email')}. Please check your spam folder.`
                                                                                                                                                                                                                    : "Enter your email to receive a password reset link."}
                                                                                                                                                                                                                              </CardDescription>
                                                                                                                                                                                                                                      </CardHeader>
                                                                                                                                                                                                                                              <CardContent>
                                                                                                                                                                                                                                                        {emailSent ? (
                                                                                                                                                                                                                                                                    <Button asChild className="w-full" variant="secondary">
                                                                                                                                                                                                                                                                                  <Link href="/login">Back to Sign In</Link>
                                                                                                                                                                                                                                                                                              </Button>
                                                                                                                                                                                                                                                                                                        ) : (
                                                                                                                                                                                                                                                                                                                    <Form {...form}>
                                                                                                                                                                                                                                                                                                                                  <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-6">
                                                                                                                                                                                                                                                                                                                                                  <FormField
                                                                                                                                                                                                                                                                                                                                                                    control={form.control}
                                                                                                                                                                                                                                                                                                                                                                                      name="email"
                                                                                                                                                                                                                                                                                                                                                                                                        render={({ field }) => (
                                                                                                                                                                                                                                                                                                                                                                                                                            <FormItem>
                                                                                                                                                                                                                                                                                                                                                                                                                                                  <FormLabel>Email</FormLabel>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <FormControl>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <Input placeholder="you@example.com" {...field} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </FormControl>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <FormMessage />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </FormItem>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <Button type="submit" className="w-full" disabled={isLoading} variant="secondary">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {isLoading && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      Get Reset Link
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </Button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </form>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </Form>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </CardContent>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </Card>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
